# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tain't What You Do
email: anton.chebotaev@gmail.com
description: >
  'Tain't what you do, it's the way that you do it, <br/>
  That's what gets results!

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://otann.com" # the base hostname & protocol for your site
twitter_username: antonotann
github_username:  otann

# Build settings
markdown: kramdown

permalink: /:categories/:title/

# Google Analytics
analytics_id: UA-74210223-1
